/**
 * Writes dist/_headers after the build.
 *
 * Cloudflare honours a `_headers` file for both Pages and Workers static
 * assets, which is how this project gets its security headers without putting
 * a Worker in the request path.
 *
 * The Content-Security-Policy has to be generated rather than checked in,
 * because `connect-src` is narrowed to the Supabase project this particular
 * build talks to — and that value is only known once VITE_SUPABASE_URL is set.
 *
 *   node scripts/gen-headers.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const DIST = path.join(ROOT, 'dist');

if (!fs.existsSync(DIST)) {
  console.error('✖ dist/ not found — run the build first.');
  process.exit(1);
}

/** Cloudflare injects build vars into the environment; .env is the local fallback. */
function readSupabaseUrl() {
  if (process.env.VITE_SUPABASE_URL) return process.env.VITE_SUPABASE_URL;

  const envFile = path.join(ROOT, '.env');
  if (!fs.existsSync(envFile)) return '';

  const match = fs
    .readFileSync(envFile, 'utf8')
    .match(/^VITE_SUPABASE_URL=(.*)$/m);
  return match ? match[1].trim().replace(/^["']|["']$/g, '') : '';
}

let supabaseOrigin = '';
try {
  const raw = readSupabaseUrl();
  if (raw && !raw.includes('your-project-ref')) supabaseOrigin = new URL(raw).origin;
} catch {
  supabaseOrigin = '';
}

const supabaseWs = supabaseOrigin.replace(/^https:/, 'wss:');

const csp = [
  "default-src 'self'",
  // Vite emits no inline scripts in production, but the module-preload shim
  // is inlined into index.html, so 'unsafe-inline' is required here.
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com data:",
  "img-src 'self' data: blob: https:",
  `connect-src 'self' ${supabaseOrigin} ${supabaseWs}`.replace(/\s+/g, ' ').trim(),
  "frame-ancestors 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const contents = `# Generated by scripts/gen-headers.mjs — do not edit by hand.
# The CSP below is scoped to the Supabase project this build was made against.

/*
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Content-Security-Policy: ${csp}

# Vite content-hashes everything under /assets, so it can be cached forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# The shell must never be cached, or a deploy keeps serving stale asset links.
/index.html
  Cache-Control: no-cache, must-revalidate
`;

fs.writeFileSync(path.join(DIST, '_headers'), contents);

console.log('✓ dist/_headers written');
console.log(
  supabaseOrigin
    ? `  connect-src scoped to ${supabaseOrigin}`
    : '  ⚠ VITE_SUPABASE_URL was not set — connect-src is \'self\' only, so the\n' +
      "    app will not be able to reach Supabase. Set it in the build environment.",
);
